name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check
        uses: coralogix/eng-gh-action-protolock@v0.1
        with:
          operation: check
          token: ${{ secrets.GITHUB_TOKEN }}

