name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buf setup
        uses: bufbuild/buf-setup-action@v0.5.0

      - name: Lint
        uses: bufbuild/buf-lint-action@v1

      - name: Check breaking changes
        uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=master'

